export const quoteList = [
    { quote: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", author: "AAAAAAAAA" },
    { quote: "Paz, é a maior das mentiras", author: "Aaatrox" },
    { quote: "Devo fazer sua pulsação subir ou sumir?", author: "Ahri" },
    { quote: "O coração é o músculo mais forte", author: "Braum" },
    { quote: "Visão é a chave da vitória... pedra tambem", author: "Braum" },
    { quote: "A palavra certa corta mais profundamente que uma faca", author: "Camille" },
    { quote: "Nana nenem eu vim pra te matar...", author: "Camille" },
    { quote: "Rapaz.. Eu sou demais!", author: "Draven" },
    { quote: "O lançe não é quanto tempo você tem, mas como você usa", author: "Ekko" },
    { quote: "Quem precisa de mapas?", author: "Ezreal" },
    { quote: "Seu lugar é no museu", author: "Ezreal" },
    { quote: "Se é você que vai pagar, eu tô dentro!", author: "Gragas" },
    { quote: "Calma, amigo", author: "Graves" },
    { quote: "Quem vai encarar o campeão?", author: "Jax" },
    { quote: "Eu luto por um futuro iluminado", author: "Jayce" },
    { quote: "Nunca um passo em falso", author: "Jayce" },
    { quote: "Num massacre floresço, como uma flor no amanhecer", author: "Jhin" },
    { quote: "Sua vida não tinha valor antes de mim", author: "Jhin" },
    { quote: "Digam olá para meus amigos de vários tamanhos", author: "Jinx" },
    { quote: "Regras são feitas para serem quebradas. Igual prédios... Ou pessoas!", author: "Jinx" },
    { quote: "Levante-se, persista e vá pra cima", author: "Kai'sa" },
    { quote: "Seu espirito é algo que ninguem pode tirar de você", author: "Karma" },
    { quote: "A violência resolve tudo", author: "Katarina" },
    { quote: "FASCÍNORA!", author: "Kayle" },
    { quote: "Domine a sí mesmo e dominará o inimigo", author: "Lee Sin" },
    { quote: "Se você pode sorrir pode tambem iluminar", author: "Lux" },
    { quote: "Vamos iluminar isso aqui", author: "Lux" },
    { quote: "Olhe para o seu interior", author: "Master Yi" },
    { quote: "Dúvida é o maior inimigo", author: "Master Yi" },
    { quote: "A mente concentrada pode perfurar rochas", author: "Master Yi" },
    { quote: "Um verdadeiro mestre é um eterno aprendiz", author: "Master Yi" },
    { quote: "O segredo para a imortalidade?  Não morra!", author: "Master Yi" },
    { quote: "Raiva dá motivação sem propósito", author: "Master Yi" },
    { quote: "O ciclo da vida e da morte continua, nós viveremos, eles morrerão", author: "Nasus" },
    { quote: "Não irrite o Yeti. Não vai gostar de ver ele irritado.", author: "Nunu" },
    { quote: "O que vale mais? Um quilo de carne ou um galão de sangue?", author: "Pyke" },
    { quote: "Olho neles!", author: "Quinn" },
    { quote: "Ok", author: "Rammus" },
    { quote: "Enquanto eu viver,todos morrerão", author: "Renekton" },
    { quote: "A violencia só gera violencia", author: "Riven" },
    { quote: "Viver com medo não é viver", author: "Sejuani" },
    { quote: "...", author: "Sona" },
    { quote: "Enquanto eu viver , ninguém há de sofrer", author: "Soraka" },
    { quote: "Sim, aquilo era uma banana, ninguem espera por uma banana!", author: "Soraka" },
    { quote: "A parada não é quantas vezes te derrubam, é quantas vezes você levanta", author: "Sett" },
    { quote: "Você é tão honesta quanto uma cortesã recentemente paga", author: "Tahm Kench" },
    { quote: "Tamanho não é documento", author: "Teemo" },
    { quote: "Eu? Louco? Ha! É bem capaz", author: "Thresh" },
    { quote: "Vira-latas imundos ficam na coleira", author: "Thresh" },
    { quote: "A casa sempre vence", author: "Twisted Fate" },
    { quote: "A sorte sempre me sorri", author: "Twisted Fate" },
    { quote: "Tenho dois coringas no baralho, não preciso de mais um palhaço como você", author: "Twisted Fate" },
    { quote: "Éééé meeeeeu, eu que lambi", author: "Twitch" },
    { quote: "O que não mata ainda não terminou", author: "Twitch" },
    { quote: "A morte é como o vento: está sempre ao seu lado", author: "Yasuo" },
    { quote: "E por isso que Yuumi rima com destruir", author: "Yuumi" },
  ]

export default {
    quoteList,
}


